### ISSUE TITLE
Is there way to log publicly?

### ISSUE THREAD

**Issue by burkostya** [justinian/hlog#1]
By default all logs are private. Is there option somewhere (hakkalogs API maybe) to make those public?

**Comment by justinian** [comment]
Hmm. I'm using the webhook integration, which claims it will ignore anything sent to it but the log message. The Hakka Logs FAQ references an API call (`/api/logs`) to fetch logs, but I haven't found anything about posting them. I'll ask.

**Comment by crs48** [comment]
You can add "@public" or "@anonymous" or "@private" to the body of your log and its privacy will be set accordingly.

**Comment by burkostya** [comment]
Just tried.
@smothers So without having "@blahblah" in message i can't set publicity level?
Maybe it should be availiable through API?

**Comment by crs48** [comment]
@burkostya yes and you're right. It should be available as a parameter in the webhook request payload. I'll update this issue when it's live.

**Comment by justinian** [comment]
@smothers Awesome, thanks!

**Comment by crs48** [comment]
The `state` parameter is now available for Webhooks. See the instructions for more info https://www.hakkalabs.co/logs?integrationstab=show

**Comment by justinian** [comment]
Perfect. Thanks, @smothers. I'll get that integrated soon.

**Comment by justinian** [comment]
@burkostya See the new `-priv=public` option, and/or the `default-privacy` setting in the config file.

**Comment by burkostya** [comment]
Thanks!
